FROM ubuntu:20.04
RUN apt-get update && apt-get install -y python3 python3-pip --no-install-recommends
RUN groupadd --gid 1001 appuser && useradd --uid 1001 --gid 1001 --shell /bin/bash --create-home appuser
USER appuser
WORKDIR /home/appuser
COPY requirements.txt .
RUN pip3 install -r requirements.txt || exit 1
COPY app.py .
CMD ["python3", "app.py"]

.dockerignore
*.pyc
__pycache__